### ISSUE TITLE
posix_net error compiling

### ISSUE THREAD

**Issue by sodomon2** [dhewm/dhewm3#252]
I have an error compiling the program is an error with posix_net.cpp here the error

[ 40%] Building CXX object CMakeFiles/dhewm3.dir/sys/posix/posix_net.cpp.o
/home/diego/Descargas/FPS/games/dhewm3-1.5.0/neo/sys/posix/posix_net.cpp: In member function 'int idTCP::Read(void*, int)':
/home/diego/Descargas/FPS/games/dhewm3-1.5.0/neo/sys/posix/posix_net.cpp:649:18: error: 'TEMP_FAILURE_RETRY' was not declared in this scope
  if ( ( nbytes = TEMP_FAILURE_RETRY( read( fd, data, size ) ) ) == -1 ) {
                  ^~~~~~~~~~~~~~~~~~
/home/diego/Descargas/FPS/games/dhewm3-1.5.0/neo/sys/posix/posix_net.cpp: In member function 'int idTCP::Write(void*, int)':
/home/diego/Descargas/FPS/games/dhewm3-1.5.0/neo/sys/posix/posix_net.cpp:706:18: error: 'TEMP_FAILURE_RETRY' was not declared in this scope
  if ( ( nbytes = TEMP_FAILURE_RETRY ( write( fd, data, size ) ) ) == -1 ) {
                  ^~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/dhewm3.dir/build.make:2039: CMakeFiles/dhewm3.dir/sys/posix/posix_net.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/dhewm3.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by DanielGibson** [comment]
Which operating system are you on? What compiler (version) are you using?

**Comment by sodomon2** [comment]
> Which operating system are you on? What compiler (version) are you using?

OS: Alpine Linux 
Compiler: gcc 8.3.0

**Comment by DanielGibson** [comment]
So you're probably using musl (not glibc), right?
Probably musl doesn't #define TEMP_FAILURE_ENTRY; however I'm surprised _GNU_SOURCE is #define'd then, I thought that should only be defined when using glibc and enabling GNU extensions..

Can you try replacing `#if defined(_GNU_SOURCE)` with `#if defined(_GNU_SOURCE) && defined(TEMP_FAILURE_RETRY)` in posix_net.cpp lines 647 and 704?

**Comment by sodomon2** [comment]
thank you no longer gives me the error but now gives me another here the other error

**Comment by DanielGibson** [comment]
That's sounds like a problem with your system libSDL2..
You could try commenting that #include line in /usr/include/SDL2/SDL_syswm.h out, but you should probably file a bugreport against the Alpine SDL2 package (or did you compile SDL2 yourself?) so they can hopefully fix it properly.

**Comment by sodomon2** [comment]
don't just install the alpine package don't compile it but i think i already know why is the error sdl2 is trying to find directfb.h in /usr/include but is found in /usr/include/directfb

**Comment by DanielGibson** [comment]
Also, dhewm3 shouldn't even need SDL_syswm.h - can you try the latest git code (or at least the 1.5.1pre1 code from https://github.com/dhewm/dhewm3/releases/tag/1.5.1_PRE1)?
There it's only included when *really* needed (on Windows when the windows-only tools are enabled)

**Comment by sodomon2** [comment]
the error no longer disappeared i didn't have to comment or delete just had to copy what was in /usr/include/directfb to /usr/include and that solved the problem

**Comment by sodomon2** [comment]
it's already compiled but when I want to run cdoom sees what happens

dhewm3 +set fs_game cdoom

dhewm3 1.5.0.1304 linux-x86_64 Sep 27 2019 02:24:06 using SDL v2.0.9
WARNING: terminal type 'xterm-256color' is unknown. terminal support may not work correctly
terminal support enabled ( use +set in_tty 0 to disable )
pid: 16129
1760 MB System Memory
found interface lo - loopback
found interface wlan0 - 172.16.16.20/255.255.255.0
doom using MMX & SSE & SSE2 for SIMD processing
enabling Flush-To-Zero mode
enabling Denormals-Are-Zero mode
WARNING: base path '/usr/share/dhewm3' does not exist
----- Initializing File System -----
Loaded pk4 /home/diego/.local/share/dhewm3/cdoom/cdoom_main.pk4 with checksum 0x9ff6284b
Loaded pk4 /home/diego/.local/share/dhewm3/cdoom/cdoom_maps.pk4 with checksum 0xa7bb2433
Loaded pk4 /home/diego/.local/share/dhewm3/cdoom/cdoom_models.pk4 with checksum 0x22e8b18
Loaded pk4 /home/diego/.local/share/dhewm3/cdoom/cdoom_sounds.pk4 with checksum 0xae50243c
Loaded pk4 /home/diego/.local/share/dhewm3/cdoom/cdoom_textures.pk4 with checksum 0x1be0b07f
Current search path:
/home/diego/.config/dhewm3/cdoom
/home/diego/.local/share/dhewm3/cdoom
/home/diego/.local/share/dhewm3/cdoom/cdoom_textures.pk4 (163 files)
/home/diego/.local/share/dhewm3/cdoom/cdoom_sounds.pk4 (113 files)
/home/diego/.local/share/dhewm3/cdoom/cdoom_models.pk4 (449 files)
/home/diego/.local/share/dhewm3/cdoom/cdoom_maps.pk4 (66 files)
/home/diego/.local/share/dhewm3/cdoom/cdoom_main.pk4 (456 files)
/home/diego/.config/dhewm3/base
/home/diego/.local/share/dhewm3/base
Addon pk4s:
shutting down: Couldn't load default.cfg
AL lib: (WW) alcSetError: Error generated on device 0, code 0xa002
AL lib: (WW) alcSetError: Error generated on device 0, code 0xa001
idRenderSystem::Shutdown()
Shutting down OpenGL subsystem
Sys_Error: Couldn't load default.cfg
shutdown terminal support

**Comment by DanielGibson** [comment]
do you also have the main doom3 game data?
the stuff that goes into base/?
das plain doom3 (without `+set fs_game cdoom`) work?

**Comment by sodomon2** [comment]
the original data of doom3 not but the data of cdoom

**Comment by DanielGibson** [comment]
???

**Comment by sodomon2** [comment]
> ???

that I don't have the data from the original game.

**Comment by DanielGibson** [comment]
You need to data of the original game to play the mods - except for Fitz Packerton, that works standalone.
You can buy the game on Steam: https://store.steampowered.com/app/9050/DOOM_3/
(Yes this, **not** Doom3BFG, that's incompatible with dhewm3 and the mods)

There's also a free demo version that works with dhewm3 1.5.1pre1 (and newer, like current git), but it doesn't work with mods.
https://dhewm3.org/#a-first-prerelease-of-dhewm3-1.5.1 has links for the Demo

**Comment by sodomon2** [comment]
I have another error compiling version 1.5.0.1_PRE1 here the error

Scanning dependencies of target dhewm3
[ 10%] Building CXX object CMakeFiles/dhewm3.dir/sys/posix/posix_main.cpp.o
[ 10%] Linking CXX executable dhewm3
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: CMakeFiles/dhewm3.dir/sys/posix/posix_main.cpp.o: in function `signalhandlerCrash(int)':
/home/diego/Descargas/FPS/games/dhewm3-1.5.1_PRE1/neo/sys/posix/posix_main.cpp:387: undefined reference to `backtrace'
/usr/lib/gcc/x86_64-alpine-linux-musl/8.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /home/diego/Descargas/FPS/games/dhewm3-1.5.1_PRE1/neo/sys/posix/posix_main.cpp:388: undefined reference to `backtrace_symbols'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/dhewm3.dir/build.make:2419: dhewm3] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/dhewm3.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by DanielGibson** [comment]
so musl doesn't have that either....

can you try replacing posix_main.cpp line 365 with
`#if ( defined(__linux__) && defined(__GLIBC__) ) || defined(__FreeBSD__) || defined(__APPLE__)`
?

**Comment by sodomon2** [comment]
OK thank you again

**Comment by DanielGibson** [comment]
Tell me if/when it all works, then I'll commit the fixes for musl

**Comment by sodomon2** [comment]
if it already works
